version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mi6CustomerCare"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-idsun2y2d90j"
s3_prefix = "mi6CustomerCare"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
